<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Model.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entry\" />
    <Folder Include="User\" />
  </ItemGroup>

</Project>
