<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Common.fs" />
    <Compile Include="Entry\RepositoryContract.fs" />
    <Compile Include="Entry\Entry.fs" />
    <Compile Include="User\RepositoryContract.fs" />
    <Compile Include="User\User.fs" />
    <Compile Include="CrossValidation.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Model\Model.fsproj" />
  </ItemGroup>

</Project>
