module DrizzleCarton.Model

open Giraffe
open Thoth.Json.Net

/// convert to Json
let json<'T> (x : 'T): HttpHandler =
    let encoded = Encode.Auto.toString(4, x)
    setHttpHeader "Content-Type" "application/json"
        >=> setBodyFromString encoded

let fromJson<'T> = Decode.Auto.fromString<'T>

type User = {
    Id: int // generated by database when adding user
    Username: string // may not contain spaces, may not include the text "drizzle" or "carton"
    Quota: int // must be a positive number greater than 1024 * 1024 (1 megabyte)
    RootFolder: int // must be the identifier of a folder with the name "files" that has no parent entry
}

let resToOpt<'T, 'Error, 'U> (f: 'T -> 'U) (res: Result<Option<'T>, 'Error>): Option<'U> =
    res
    |> Result.defaultValue None
    |> Option.map f

module User =
    let private toUser (id, username, quota, rootFolder) =
        {
            User.Id = id
            Username = username
            Quota = quota
            RootFolder = rootFolder
        }

    let fetch (db: Database) (id: int) =
        Database.user id db
        |> Result.map toUser

    let all (db: Database) =
        let result = Database.users db
        match result with
        | Ok users ->
            users |> List.map toUser
        | Error _ -> []

    let toTuple (user: User) =
         user.Id, user.Username, user.Quota, user.RootFolder

    let add (db: Database) username quota rootFolder =
        Database.addUser db (username, quota, rootFolder)
        |> Result.map toUser

    let update (db : Database) id user =
        Database.updateUser db (toTuple user)
        |> Result.map toUser

type Entry = {
    Id: int // generated by the database
    Name: string // names may not contain slashes or backslashes
    Parent: Option<int> // may only be None for the root folder
    Kind: string // must be "folder" or "file"
    Size: int // must be greater than or equal to 0.
              // folders always have a size of 0
}


module Entry =
    let private toEntry (id, name, parent, kind, size) =
        { Entry.Id = id
          Name = name
          Parent = parent
          Kind  = kind
          Size = size
        }

    let newRoot (db: Database) =
        Database.addEntry db ("files", None, "folder", 0)
        |> Result.map toEntry

    let fetch (db : Database) (id: int) =
        Database.entry db id
        |> Result.map toEntry


    let fetchSubentries (db : Database) (id: int) =
        Database.subEntries db id
        |> Result.defaultValue []
        |> List.map toEntry
