namespace DrizzleCarton.Model

open Validation

type ByteCount = ByteCount of int

type EntryId = private EntryId of int // generated by the database
type EntryName = private EntryName of string
type EntryParent = private EntryParent of EntryId option

type EntryKind =
  | Folder
  | File

type EntrySize = private EntrySize of ByteCount

type EntryData =
  private
    { Name: EntryName
      Parent: EntryParent
      Kind: EntryKind
      Size: EntrySize }

type Entry =
  private { Id: EntryId; Data: EntryData }

[<RequireQualifiedAccess>]
module EntryId =
  let first = EntryId 1

  let validate id =
    id
    |> notBelowOne "Entry id cannot be less than 1."
    |> Result.mapError ValidationError

  let ofRaw id = validate id |> Result.map EntryId

  let toRaw (EntryId(eid)) = eid

[<RequireQualifiedAccess>]
module EntryName =
  let root = EntryName "files"

  let ofRaw (name: string) =
    name
    |> nonEmpty "Entry name may not be empty."
    |> Result.bind (fun n ->
      if n.Length > 64 then
        Error "Entry name may not be longer than 64 characters."
      else
        Ok n)
    |> Result.bind (noForwardSlashes "Entry name may not contain forward slashes.")
    |> Result.bind (noBackwardSlashes "Entry name may not contain backward slashes.")
    |> Result.map EntryName
    |> Result.mapError ValidationError

  let toRaw (EntryName(name)) = name

[<RequireQualifiedAccess>]
module EntryParent =
  let none = EntryParent None

  let ofRaw (parent: int option) =
    match parent with
    | Some id ->
      match EntryId.ofRaw id with
      | Error e -> Error e
      | Ok entryId -> Some entryId |> EntryParent |> Ok
    | None -> Ok none

  let toRaw (EntryParent(parent)) = parent

[<RequireQualifiedAccess>]
module EntryKind =

  let ofRaw kind =
    kind
    |> nonEmpty "Entry kind may not be empty."
    |> Result.bind (fun k ->
      match k with
      | "folder" -> Ok Folder
      | "file" -> Ok File
      | _ -> Error "Entry kind must be either 'file' or 'folder'.")
    |> Result.mapError ValidationError

  let toRaw kind =
    match kind with
    | File -> "file"
    | Folder -> "folder"

[<RequireQualifiedAccess>]
module EntrySize =
  let zero = EntrySize(ByteCount 0)

  let ofRaw size =
    size
    |> nonNegativeNumber "Entry size may not be less than zero."
    |> Result.map (fun s -> EntrySize(ByteCount s))
    |> Result.mapError ValidationError

  let toRaw (EntrySize(ByteCount c)) = c

[<RequireQualifiedAccess>]
module Entry =

  let hasParent entry = entry.Parent <> EntryParent.none

  let isFolder entry = entry.Kind = Folder

  let isSizeZero entry = entry.Size = EntrySize.zero

  let isRootFolder entry =
    entry |> isFolder && not (entry |> hasParent)

  module Validation =

    let nonFile invalid entry =
      if entry |> isFolder then Ok entry else Error invalid

    let folderSizeIsZero invalid entry =
      if entry |> isFolder && not (entry |> isSizeZero) then
        Error invalid
      else
        Ok entry

    let folderWithoutParentHasRootName invalid entry =
      if entry |> isFolder && not (entry |> hasParent) && entry.Name <> EntryName.root then
        Error invalid
      else
        Ok entry

    let noParentOfRootFolder invalid entry =
      if hasParent entry && entry |> isFolder && entry.Name = EntryName.root then
        Error invalid
      else
        Ok entry

    let nonRootEntryHasParent invalid entry =
      if not (isRootFolder entry) && not (hasParent entry) then
        Error invalid
      else
        Ok entry

  [<RequireQualifiedAccess>]
  module EntryData =
    let root =
      { Name = EntryName.root
        Parent = EntryParent.none
        Kind = EntryKind.Folder
        Size = EntrySize.zero }

    let make (name, parent, kind, size) : Result<EntryData, ValidationError> =
      { Name = name
        Parent = parent
        Kind = kind
        Size = size }
      |> Validation.folderSizeIsZero "Folders must have a size of zero."
      |> Result.bind (Validation.folderWithoutParentHasRootName "A folder without a parent must be named 'files'.")
      |> Result.bind (Validation.noParentOfRootFolder "Root folders may not have a parent.")
      |> Result.bind (Validation.nonRootEntryHasParent "Non-root entries must have a parent.")
      |> Result.mapError Validation.ValidationError

    let ofRaw (rawName, rawParent, rawKind, rawSize) : Result<EntryData, ValidationError> =
      EntryName.ofRaw rawName
      |> Result.bind (fun entryName ->
        EntryParent.ofRaw rawParent
        |> Result.bind (fun entryParent ->
          EntryKind.ofRaw rawKind
          |> Result.bind (fun entryKind ->
            EntrySize.ofRaw rawSize
            |> Result.map (fun entrySize -> (entryName, entryParent, entryKind, entrySize)))))
      |> Result.bind make

    let toTuple data =
      data.Name, data.Parent, data.Kind, data.Size

    let toRawTuple data =
      EntryName.toRaw data.Name,
      EntryParent.toRaw data.Parent |> Option.map EntryId.toRaw,
      EntryKind.toRaw data.Kind,
      EntrySize.toRaw data.Size

  let getData entry = entry.Data

  let getId entry = entry.Id

  let withId (data: EntryData) (id: EntryId) = { Id = id; Data = data }

  let make (id, name, parent, kind, size) =
    EntryData.make (name, parent, kind, size)
    |> Result.map (fun data -> withId data id)

  let ofRaw (rawId, rawName, rawParent, rawKind, rawSize) =
    EntryId.ofRaw rawId
    |> Result.bind (fun entryId ->
      EntryData.ofRaw (rawName, rawParent, rawKind, rawSize)
      |> Result.map (fun entryData -> withId entryData entryId))

  let toTuple (entry: Entry) =
    entry.Id, entry.Data.Name, entry.Data.Parent, entry.Data.Kind, entry.Data.Size

  let toRawTuple entry =
    EntryId.toRaw entry.Id,
    EntryName.toRaw entry.Data.Name,
    EntryParent.toRaw entry.Data.Parent |> Option.map EntryId.toRaw,
    EntryKind.toRaw entry.Data.Kind,
    EntrySize.toRaw entry.Data.Size
