namespace DrizzleCarton.Model

type Entry =
  { Id: int // generated by the database
    Name: string // names may not contain slashes or backslashes
    Parent: Option<int> // may only be None for the root folder
    Kind: string // must be "folder" or "file"
    Size: int  // must be greater than or equal to 0.
  // folders always have a size of 0
  }

module Entry =
  let private toEntry (id, name, parent, kind, size) =
    { Entry.Id = id
      Name = name
      Parent = parent
      Kind = kind
      Size = size }

  let newRoot (db: Database) =
    Database.addEntry db ("files", None, "folder", 0) |> Result.map toEntry

  let fetch (db: Database) (id: int) =
    Database.entry db id |> Result.map toEntry


  let fetchSubentries (db: Database) (id: int) =
    Database.subEntries db id |> Result.defaultValue [] |> List.map toEntry
