namespace DrizzleCarton.Model

type EntryId = private EntryId of int // generated by the database

type EntryName = private EntryName of string

type EntryParent = private EntryParent of Option<int> // may only be None for the root folder

type EntryKind =
  | Folder
  | File

type EntrySize = private EntrySize of int // Folders always have a size of 0.

[<RequireQualifiedAccess>]
module EntryId =
  let ofRaw id =
    (if id < 1 then
       Error "Entry id cannot be less than 1."
     else
       Ok id)
    |> Result.map EntryId

  let toRaw (EntryId(eid)) = eid

  let first = EntryId 1

[<RequireQualifiedAccess>]
module EntryName =
  let ofRaw (name: string) =
    name
    |> Validation.nonEmpty "Entry name may not be empty."
    |> Result.bind (fun n ->
      if n.Length > 64 then
        Error "Entry name may not be longer than 64 characters."
      else
        Ok n)
    |> Result.bind (Validation.noForwardSlashes "Entry name may not contain forward slashes.")
    |> Result.bind (Validation.noBackwardSlashes "Entry name may not contain backward slashes.")
    |> Result.map EntryName

  let toRaw (EntryName(name)) = name

[<RequireQualifiedAccess>]
module EntryParent =
  let ofRaw parent = EntryParent parent

  let toRaw (EntryParent(parent)) = parent

[<RequireQualifiedAccess>]
module EntryKind =
  let ofRaw kind =
    kind
    |> Validation.nonEmpty "Entry kind may not be empty."
    |> Result.bind (fun k ->
      match k with
      | "folder" -> Ok Folder
      | "file" -> Ok File
      | _ -> Error "Entry kind must be either 'file' or 'folder'.")

  let toRaw kind =
    match kind with
    | File -> "file"
    | Folder -> "folder"

[<RequireQualifiedAccess>]
module EntrySize =
  let ofRaw size =
    size
    |> Validation.nonNegativeNumber "Entry size cannot be less than zero."
    |> Result.map EntrySize

  let toRaw (EntrySize(size)) = size

  let zero = EntrySize 0

module Entry =

  type Entry =
    private
      { Id: EntryId
        Name: EntryName
        Parent: EntryParent
        Kind: EntryKind
        Size: EntrySize }

  let make (id, name, parent, kind, size) =
    { Id = id
      Name = name
      Parent = parent
      Kind = kind
      Size = size }
