namespace DrizzleCarton.Model

open Validation

type UserName = private UserName of string
type UserQuota = private UserQuota of int
type UserRoot = private UserRoot of Entry

type UserData =
  private
    { Name: UserName
      Quota: UserQuota
      RootFolder: UserRoot }

type UserId = private UserId of int // generated by database when adding user

type User = private { Id: UserId; Data: UserData }

[<RequireQualifiedAccess>]
module UserId =
  let first = UserId 1

  let validate id =
    id
    |> notBelowOne "User id may not be less than 1."
    |> Result.mapError ValidationError

  let ofRaw id = validate id |> Result.map UserId

  let toRaw (UserId(id)) = id

[<RequireQualifiedAccess>]
module UserName =

  let validate name =
    name
    |> nonEmpty "User name may not be empty"
    |> Result.bind (noSpaces "User name may not contain spaces.")
    |> Result.bind (fun n ->
      if n.Contains "drizzle" || n.Contains "carton" then
        Error "User name may not contain the words 'drizzle' or 'carton'."
      else
        Ok n)
    |> Result.mapError ValidationError

  let ofRaw name = validate name |> Result.map UserName

  let toRaw (UserName(name)) = name

[<RequireQualifiedAccess>]
module UserQuota =
  module Sizes =
    let KB = 1024
    let MB = 1024 * KB
    let GB = 1024 * MB

  let min = Sizes.MB // 1 megabyte
  let max = Sizes.GB // 1 gigabyte

  let validate quota =
    quota
    |> nonNegativeNumber "User quota may not be a negative number."
    |> Result.bind (fun q ->
      if q <= min || q > max then
        Error "User quota must be between 1024 * 1024 (1 megabyte) and 2^30 (1 gigabyte)."
      else
        Ok q)
    |> Result.mapError ValidationError

  let ofRaw quota = validate quota |> Result.map UserQuota

  let toRaw (UserQuota(quota)) = quota

[<RequireQualifiedAccess>]
module UserRoot =
  let validate (root: Entry) =
    (if not (Entry.isRootFolder root.Data) then
       Error "Entry must be a valid root folder to be a UserRoot."
     else
       Ok root)
    |> Result.mapError ValidationError

  let ofRaw entry = validate entry |> Result.map UserRoot

  let toRaw (UserRoot(entry)) = entry

[<RequireQualifiedAccess>]
module UserData =

  let make (name, quota, rootFolder) : Result<UserData, ValidationError> =
    { Name = name
      Quota = quota
      RootFolder = rootFolder }
    // Potential validations across fields...
    |> Ok

  let ofRaw (rawName, rawQuota, rawRoot) : Result<UserData, ValidationError> =
    UserName.ofRaw rawName
    |> Result.bind (fun userName ->
      UserQuota.ofRaw rawQuota
      |> Result.bind (fun userQuota ->
        UserRoot.ofRaw rawRoot
        |> Result.map (fun userRoot -> (userName, userQuota, userRoot))))
    |> Result.bind make

  let toTuple (data: UserData) = data.Name, data.Quota, data.RootFolder

  let toRawTuple data =
    UserName.toRaw data.Name, UserQuota.toRaw data.Quota, UserRoot.toRaw data.RootFolder |> Entry.getId |> EntryId.toRaw

[<RequireQualifiedAccess>]
module User =

  let getData user = user.Data

  let withId (data: UserData) (id: UserId) = { Id = id; Data = data }

  let make (id, name, quota, rootFolder) =
    UserData.make (name, quota, rootFolder)
    |> Result.map (fun data -> withId data id)

  let ofRaw (rawId, rawName, rawQuota, rawRoot) =
    UserId.ofRaw rawId
    |> Result.bind (fun userId ->
      UserData.ofRaw (rawName, rawQuota, rawRoot)
      |> Result.map (fun userData -> withId userData userId))

  let toTuple (user: User) =
    user.Id, user.Data.Name, user.Data.Quota, user.Data.RootFolder

  let toRawTuple user =
    UserId.toRaw user.Id,
    UserName.toRaw user.Data.Name,
    UserQuota.toRaw user.Data.Quota,
    UserRoot.toRaw user.Data.RootFolder |> Entry.getId |> EntryId.toRaw

  let rawName user = UserName.toRaw user.Data.Name

  let getRootFolderId user = 
    UserRoot.toRaw user.Data.RootFolder |> Entry.getId
