namespace DrizzleCarton.Model

open Validation

type UserName = private UserName of string
type UserQuota = private UserQuota of int
type UserRoot = private UserRoot of EntryId

type UserData =
  private
    { Name: UserName
      Quota: UserQuota
      RootFolder: UserRoot }

type UserId = private UserId of int // generated by database when adding user

type User = private { Id: UserId; Data: UserData }

[<RequireQualifiedAccess>]
module UserId =
  let first = UserId 1

  let validate id =
    id
    |> notBelowOne "User id may not be less than 1."
    |> Result.mapError ValidationError

  let ofRaw id = validate id |> Result.map UserId

  let toRaw (UserId(id)) = id

[<RequireQualifiedAccess>]
module UserName =

  let validate name =
    name
    |> nonEmpty "User name may not be empty"
    |> Result.bind (noSpaces "User name may not contain spaces.")
    |> Result.bind (fun n ->
      if n.Contains "drizzle" || n.Contains "carton" then
        Error "User name may not contain the words 'drizzle' or 'carton'."
      else
        Ok n)
    |> Result.mapError ValidationError

  let ofRaw name = validate name |> Result.map UserName

  let toRaw (UserName(name)) = name

[<RequireQualifiedAccess>]
module UserQuota =
  let min = 1024 * 1024 // 1 megabyte
  let max = 2 <<< 30 // 1 gigabyte

  let validate quota =
    quota
    |> nonNegativeNumber "User quota may not be a negative number."
    |> Result.bind (fun q ->
      if q <= min || q > max then
        Error "User quota must be between 1024 * 1024 (1 megabyte) and 2^30 (1 gigabyte)."
      else
        Ok q)
    |> Result.mapError ValidationError

  let ofRaw quota = validate quota |> Result.map UserQuota

  let toRaw (UserQuota(quota)) = quota

// TODO: Invariant that must be enforced by Application layer: Must be the identifier of a folder with the name "files" that has no parent entry
[<RequireQualifiedAccess>]
module UserRoot =
  let ofRaw id = UserRoot id |> Ok

  let toRaw (UserRoot(id)) = id

[<RequireQualifiedAccess>]
module UserData =

  let make (name, quota, rootFolder) : Result<UserData, ValidationError> =
    { Name = name
      Quota = quota
      RootFolder = rootFolder }
    // Potential validations across fields...
    |> Ok

  let ofRaw (rawName, rawQuota, rawRootId) : Result<UserData, ValidationError> =
    UserName.ofRaw rawName
    |> Result.bind (fun userName ->
      UserQuota.ofRaw rawQuota
      |> Result.bind (fun userQuota ->
        UserRoot.ofRaw rawRootId
        |> Result.map (fun userRoot -> (userName, userQuota, userRoot))))
    |> Result.bind make

  let toTuple (data: UserData) = data.Name, data.Quota, data.RootFolder

[<RequireQualifiedAccess>]
module User =

  let giveId (data: UserData) (id: UserId) = { Id = id; Data = data }

  let make (id, name, quota, rootFolder) =
    UserData.make (name, quota, rootFolder)
    |> Result.map (fun data -> giveId data id)

  let ofRaw (rawId, rawName, rawQuota, rawRootId) =
    UserId.ofRaw rawId
    |> Result.bind (fun id ->
      UserData.ofRaw (rawName, rawQuota, rawRootId)
      |> Result.map (fun data -> giveId data id))

  let toTuple (user: User) =
    user.Id, user.Data.Name, user.Data.Quota, user.Data.RootFolder
