namespace DrizzleCarton.Model

type UserId = private UserId of int // generated by database when adding user
type UserName = private UserName of string
type UserQuota = private UserQuota of int
type UserRoot = private UserRoot of EntryId

type User =
  private
    { Id: UserId
      Username: UserName
      Quota: UserQuota
      RootFolder: UserRoot }

[<RequireQualifiedAccess>]
module UserId =
  let first = UserId 1

  open Validation

  let validate id =
    id
    |> notBelowOne "User id may not be less than 1."
    |> Result.mapError ValidationError

  let ofRaw id = validate id |> Result.map UserId

  let toRaw (UserId(id)) = id

[<RequireQualifiedAccess>]
module UserName =
  open Validation

  let validate name =
    name
    |> nonEmpty "User name may not be empty"
    |> Result.bind (noSpaces "User name may not contain spaces.")
    |> Result.bind (fun n ->
      if n.Contains "drizzle" || n.Contains "carton" then
        Error "User name may not contain the words 'drizzle' or 'carton'."
      else
        Ok n)
    |> Result.mapError ValidationError

  let ofRaw name = validate name |> Result.map UserName

  let toRaw (UserName(name)) = name

[<RequireQualifiedAccess>]
module UserQuota =
  let min = 1024 * 1024 // 1 megabyte
  let max = 2 <<< 30 // 1 gigabyte

  open Validation

  let validate quota =
    quota
    |> nonNegativeNumber "User quota may not be a negative number."
    |> Result.bind (fun q ->
      if q <= min || q > max then
        Error "User quota must be between 1024 * 1024 (1 megabyte) and 2^30 (1 gigabyte)."
      else
        Ok q)
    |> Result.mapError ValidationError

  let ofRaw quota = validate quota |> Result.map UserQuota

  let toRaw (UserQuota(quota)) = quota

// TODO: Invariant that must be enforced by Application layer: Must be the identifier of a folder with the name "files" that has no parent entry
[<RequireQualifiedAccess>]
module UserRoot =
  let ofRaw id = UserRoot id |> Ok

  let toRaw (UserRoot(id)) = id

[<RequireQualifiedAccess>]
module User =

  let make (id, name, quota, rootFolder) : Result<User, Validation.ValidationError> =
    { Id = id
      Username = name
      Quota = quota
      RootFolder = rootFolder }
    |> Ok

  let ofRaw (id, name, quota, rootFolder) =
    UserId.ofRaw id
    |> Result.bind (fun userId ->
      UserName.ofRaw name
      |> Result.bind (fun userName ->
        UserQuota.ofRaw quota
        |> Result.bind (fun userQuota ->
          UserRoot.ofRaw rootFolder
          |> Result.map (fun userRoot -> (userId, userName, userQuota, userRoot)))))
    |> Result.bind make

  let toTuple (user: User) =
    user.Id, user.Username, user.Quota, user.RootFolder
