<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="User\User.fs" />
    <Compile Include="SimulatedDatabase.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entry\" />
  </ItemGroup>

</Project>
